### ISSUE TITLE
Extension doesn't work with codelens

### ISSUE THREAD

**Issue by paladin2005** [idanpa/vscode-smartmulticursor#1]
In class with codelens, the smart cursor doesn't work.
Please support it.

**Comment by idanpa** [comment]
@paladin2005 thanks for reporting this issue. 
Could you please explain how to reproduce? 
I tried and it skips codelens lines correctly:
![codelens_working](https://user-images.githubusercontent.com/17422884/62544771-b71ccd00-b860-11e9-849c-d4e554377e8f.gif)

**Comment by idanpa** [comment]
I'm closing this issue, please let me know if you have any problems.
