### ISSUE TITLE
New feature to move last cursor left/right

### ISSUE THREAD

**Issue by lilole** [idanpa/vscode-smartmulticursor#12]
I actually added the code for this already and have been using it a couple years. It was something I was missing from Atom so instead of complaining I fixed it. You're welcome.  :slightly_smiling_face: 

https://github.com/idanpa/vscode-smartmulticursor/pull/8

Basically, after adding a new cursor above or below, this change allows moving that new cursor left or right as needed.

Please let me know if you need anything more from me about this. Regards.

**Comment by idanpa** [comment]
Merged your changes. Thanks! ❤️
