### ISSUE TITLE
Where it will place the cursor?

### ISSUE THREAD

**Issue by MuhammadimYusoff** [idanpa/vscode-smartmulticursor#4]
I used the shortcut provided by your documentation, cmd + alt + Up/Down.

But I can't even know where it will place the cursor, just randomly?!

I placed it at the end of line, which in my case AFTER a comma 
`(line 1)ColorSwatch(0xFF8899A8, { <Cursor Here 1> 
     (line 2) 'highlight': Color(0xFF8899A8), <Cursor Here 2>
     (line 3) 'splash': Color(0xFFA9CAE8),
   (line 4) }),`

1) I placed my cursor at the marked place Cursor Number 1, pressed the shortcut key 'Down' and it appear AFTER the comma?

2) I placed my cursor at the marked place Cursor Number 2, pressed the shortcut key 'Up' and it appear ALSO AFTER the comma?!?

3) Even if I placed my cursor EXACTLY at number 8, pressed the shortcut key, it still NOT ALIGN.

So how can I place the Cursor EXACTLY AT NUMBER 8?
Thanks.

**Comment by adawolfs** [comment]
Got the same at the start, just found that bindings was configured as "alt+shift+up/down"

**Comment by idanpa** [comment]
@adawolfs this is a new and unrelated issue, on windows the keybinding should be ctrl+alt+up/down (override the default multiple cursors).
I'll check what went wrong (on package.json it seems fine).
@MuhammadimYusoff  sorry for the late response, but what is the behavior you are expecting in this scenario?

**Comment by idanpa** [comment]
@adawolfs problem should be fixed in 0.0.4, please let me know if you still have issues.
